### ISSUE TITLE
Como gerar o apk?

### ISSUE THREAD

**Issue by FNakano** [shis218/BlindOP#1]
Olá!
    Clonei o repositório e executei (no linux) `sh gradlew` o resultado está abaixo. Tentei listar as tarefas com `sh gradlew tasks` mas ele falha. O `.apk` não é gerado. Consultei a documentação (https://developer.android.com/studio/build/building-cmdline), sem sucesso. 
   Testei também com `~/.gradle/wrapper/dists/gradle-6.1.1-all/cfmwm155h49vnt3hynmlrsdst/gradle-6.1.1/bin/gradle tasks`, que executa mais diretamente a versão instalada, mas a mensagem de erro é a mesma que recebo de `sh gradlew tasks`.

    Como gerar o `.apk`?

<pre><font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~</b></font>$ cd Documentos/git/
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git</b></font>$ git clone https://github.com/shis218/BlindOP.git
Cloning into &apos;BlindOP&apos;...
remote: Enumerating objects: 137, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 137 (delta 24), reused 136 (delta 23), pack-reused 0
Receiving objects: 100% (137/137), 822.76 KiB | 366.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git</b></font>$ cd BlindOP/
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ ls
<font color="#268BD2"><b>app</b></font>           <font color="#268BD2"><b>Diagramas</b></font>  gradle.properties  gradlew.bat
build.gradle  <font color="#268BD2"><b>gradle</b></font>     gradlew            settings.gradle
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew
Downloading https://services.gradle.org/distributions/gradle-6.1.1-all.zip
....................................................................................................................................
Unzipping /home/fabio/.gradle/wrapper/dists/gradle-6.1.1-all/cfmwm155h49vnt3hynmlrsdst/gradle-6.1.1-all.zip to /home/fabio/.gradle/wrapper/dists/gradle-6.1.1-all/cfmwm155h49vnt3hynmlrsdst
Set executable permissions for: /home/fabio/.gradle/wrapper/dists/gradle-6.1.1-all/cfmwm155h49vnt3hynmlrsdst/gradle-6.1.1/bin/gradle

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle&apos;s documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

<b>&gt; Task :help</b>

Welcome to Gradle 6.1.1.

To run a build, run <b>gradlew &lt;task&gt; ...</b>

To see a list of available tasks, run <b>gradlew tasks</b>

To see a list of command-line options, run <b>gradlew --help</b>

To see more detail about a task, run <b>gradlew help --task &lt;task&gt;</b>

For troubleshooting, visit <b>https://help.gradle.org</b>

<font color="#859900"><b>BUILD SUCCESSFUL</b></font> in 2m 55s
1 actionable task: 1 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ 

</pre>

<pre>
Welcome to Gradle 6.1.1.

To run a build, run <b>gradlew &lt;task&gt; ...</b>

To see a list of available tasks, run <b>gradlew tasks</b>

To see a list of command-line options, run <b>gradlew --help</b>

To see more detail about a task, run <b>gradlew help --task &lt;task&gt;</b>

For troubleshooting, visit <b>https://help.gradle.org</b>

<font color="#859900"><b>BUILD SUCCESSFUL</b></font> in 2m 55s
1 actionable task: 1 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ gradlew tasks

Comando &apos;gradlew&apos; não encontrado, você quis dizer:

  comando &apos;gradle&apos; do snap gradle (6.8.3)
  comando &apos;gradle&apos; do deb gradle (4.4.1-10)

Veja &apos;snap info &lt;snapname&gt;&apos; para versões adicionais.

<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew tasks

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

<font color="#DC322F"><b>&gt; Task :tasks</b></font><font color="#DC322F"> FAILED</font>

<b>------------------------------------------------------------</b>
<b>Tasks runnable from root project</b>
<b>------------------------------------------------------------</b>

<font color="#DC322F">FAILURE: Build failed with an exception.</font>

* What went wrong:
Execution failed for task &apos;:tasks&apos;.
<font color="#B58900">&gt; </font>Could not create task &apos;:app:lint&apos;.
   <font color="#B58900">&gt; </font>SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project&apos;s local properties file at &apos;/home/fabio/Documentos/git/BlindOP/local.properties&apos;.

* Try:
Run with <b>--stacktrace</b> option to get the stack trace. Run with <b>--info</b> or <b>--debug</b> option to get more log output. Run with <b>--scan</b> to get full insights.

* Get more help at <b>https://help.gradle.org</b>

<font color="#DC322F"><b>BUILD FAILED</b></font> in 1s
1 actionable task: 1 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ 

</pre>

**Comment by shis218** [comment]
SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/fabio/Documentos/git/BlindOP/local.properties'.

Creio que precise instalar a sdk e configurar a variavel de ambiente manualmente, no windows quando instalei o android studio ele já instalou a sdk e o avd sem problemas.


Para criar o apk, no menu build possui as opções Build Bundle(s) / APK(s) > Build APK(s) e ele estara na pasta 
'app\build\outputs\apk'

**Comment by FNakano** [comment]
Sim, tem razão. Depois de instalar o android sdk (feito indiretamente quando criei o projeto no IntelliJ), criei a variável de ambiente e tentei `gradlew tasks`. Fiquei sem saber se deveria usar `gradlew bundle` ou `gradlew assemble`. O primeiro não gerou o `.apk`, mas o segundo gerou. 

Resolvido.

<pre><font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew tasks

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

<font color="#DC322F"><b>&gt; Task :tasks</b></font><font color="#DC322F"> FAILED</font>

<b>------------------------------------------------------------</b>
<b>Tasks runnable from root project</b>
<b>------------------------------------------------------------</b>


<font color="#DC322F">FAILURE: Build failed with an exception.</font>

* What went wrong:
Execution failed for task &apos;:tasks&apos;.
<font color="#B58900">&gt; </font>Could not create task &apos;:app:lint&apos;.
   <font color="#B58900">&gt; </font>SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project&apos;s local properties file at &apos;/home/fabio/Documentos/git/BlindOP/local.properties&apos;.

* Try:
Run with <b>--stacktrace</b> option to get the stack trace. Run with <b>--info</b> or <b>--debug</b> option to get more log output. Run with <b>--scan</b> to get full insights.

* Get more help at <b>https://help.gradle.org</b>

<font color="#DC322F"><b>BUILD FAILED</b></font> in 827ms
1 actionable task: 1 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ export ANDROID_SDK_ROOT=/home/fabio/Android
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew tasks

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

<b>&gt; Task :tasks</b>

<b>------------------------------------------------------------</b>
<b>Tasks runnable from root project</b>
<b>------------------------------------------------------------</b>

<b>Android tasks</b>
<b>-------------</b>
<font color="#859900">androidDependencies</font><font color="#B58900"> - Displays the Android dependencies of the project.</font>
<font color="#859900">signingReport</font><font color="#B58900"> - Displays the signing info for the base and test modules</font>
<font color="#859900">sourceSets</font><font color="#B58900"> - Prints out all the source sets defined in this project.</font>

<b>Build tasks</b>
<b>-----------</b>
<font color="#859900">assemble</font><font color="#B58900"> - Assemble main outputs for all the variants.</font>
<font color="#859900">assembleAndroidTest</font><font color="#B58900"> - Assembles all the Test applications.</font>
<font color="#859900">build</font><font color="#B58900"> - Assembles and tests this project.</font>
<font color="#859900">buildDependents</font><font color="#B58900"> - Assembles and tests this project and all projects that depend on it.</font>
<font color="#859900">buildNeeded</font><font color="#B58900"> - Assembles and tests this project and all projects it depends on.</font>
<font color="#859900">bundle</font><font color="#B58900"> - Assemble bundles for all the variants.</font>
<font color="#859900">clean</font><font color="#B58900"> - Deletes the build directory.</font>
<font color="#859900">cleanBuildCache</font><font color="#B58900"> - Deletes the build cache directory.</font>
<font color="#859900">compileDebugAndroidTestSources</font>
<font color="#859900">compileDebugSources</font>
<font color="#859900">compileDebugUnitTestSources</font>
<font color="#859900">compileReleaseSources</font>
<font color="#859900">compileReleaseUnitTestSources</font>

<b>Build Setup tasks</b>
<b>-----------------</b>
<font color="#859900">init</font><font color="#B58900"> - Initializes a new Gradle build.</font>
<font color="#859900">wrapper</font><font color="#B58900"> - Generates Gradle wrapper files.</font>

<b>Cleanup tasks</b>
<b>-------------</b>
<font color="#859900">lintFix</font><font color="#B58900"> - Runs lint on all variants and applies any safe suggestions to the source code.</font>

<b>Help tasks</b>
<b>----------</b>
<font color="#859900">buildEnvironment</font><font color="#B58900"> - Displays all buildscript dependencies declared in root project &apos;blindop&apos;.</font>
<font color="#859900">components</font><font color="#B58900"> - Displays the components produced by root project &apos;blindop&apos;. [incubating]</font>
<font color="#859900">dependencies</font><font color="#B58900"> - Displays all dependencies declared in root project &apos;blindop&apos;.</font>
<font color="#859900">dependencyInsight</font><font color="#B58900"> - Displays the insight into a specific dependency in root project &apos;blindop&apos;.</font>
<font color="#859900">dependentComponents</font><font color="#B58900"> - Displays the dependent components of components in root project &apos;blindop&apos;. [incubating]</font>
<font color="#859900">help</font><font color="#B58900"> - Displays a help message.</font>
<font color="#859900">model</font><font color="#B58900"> - Displays the configuration model of root project &apos;blindop&apos;. [incubating]</font>
<font color="#859900">outgoingVariants</font><font color="#B58900"> - Displays the outgoing variants of root project &apos;blindop&apos;.</font>
<font color="#859900">projects</font><font color="#B58900"> - Displays the sub-projects of root project &apos;blindop&apos;.</font>
<font color="#859900">properties</font><font color="#B58900"> - Displays the properties of root project &apos;blindop&apos;.</font>
<font color="#859900">tasks</font><font color="#B58900"> - Displays the tasks runnable from root project &apos;blindop&apos; (some of the displayed tasks may belong to subprojects).</font>

<b>Install tasks</b>
<b>-------------</b>
<font color="#859900">installDebug</font><font color="#B58900"> - Installs the Debug build.</font>
<font color="#859900">installDebugAndroidTest</font><font color="#B58900"> - Installs the android (on device) tests for the Debug build.</font>
<font color="#859900">uninstallAll</font><font color="#B58900"> - Uninstall all applications.</font>
<font color="#859900">uninstallDebug</font><font color="#B58900"> - Uninstalls the Debug build.</font>
<font color="#859900">uninstallDebugAndroidTest</font><font color="#B58900"> - Uninstalls the android (on device) tests for the Debug build.</font>
<font color="#859900">uninstallRelease</font><font color="#B58900"> - Uninstalls the Release build.</font>

<b>Verification tasks</b>
<b>------------------</b>
<font color="#859900">check</font><font color="#B58900"> - Runs all checks.</font>
<font color="#859900">connectedAndroidTest</font><font color="#B58900"> - Installs and runs instrumentation tests for all flavors on connected devices.</font>
<font color="#859900">connectedCheck</font><font color="#B58900"> - Runs all device checks on currently connected devices.</font>
<font color="#859900">connectedDebugAndroidTest</font><font color="#B58900"> - Installs and runs the tests for debug on connected devices.</font>
<font color="#859900">deviceAndroidTest</font><font color="#B58900"> - Installs and runs instrumentation tests using all Device Providers.</font>
<font color="#859900">deviceCheck</font><font color="#B58900"> - Runs all device checks using Device Providers and Test Servers.</font>
<font color="#859900">lint</font><font color="#B58900"> - Runs lint on all variants.</font>
<font color="#859900">lintDebug</font><font color="#B58900"> - Runs lint on the Debug build.</font>
<font color="#859900">lintRelease</font><font color="#B58900"> - Runs lint on the Release build.</font>
<font color="#859900">lintVitalRelease</font><font color="#B58900"> - Runs lint on just the fatal issues in the release build.</font>
<font color="#859900">test</font><font color="#B58900"> - Run unit tests for all variants.</font>
<font color="#859900">testDebugUnitTest</font><font color="#B58900"> - Run unit tests for the debug build.</font>
<font color="#859900">testReleaseUnitTest</font><font color="#B58900"> - Run unit tests for the release build.</font>

To see all tasks and more detail, run <b>gradlew tasks --all</b>

To see more detail about a task, run <b>gradlew help --task &lt;task&gt;</b>

<font color="#859900"><b>BUILD SUCCESSFUL</b></font> in 843ms
1 actionable task: 1 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew bundle

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
Observed package id &apos;build-tools;30.0.3&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/build-tools/30.0.3&apos; (Expected &apos;/home/fabio/Android/build-tools/30.0.3&apos;)
Observed package id &apos;emulator&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/emulator&apos; (Expected &apos;/home/fabio/Android/emulator&apos;)
Observed package id &apos;patcher;v4&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/patcher/v4&apos; (Expected &apos;/home/fabio/Android/patcher/v4&apos;)
Observed package id &apos;platform-tools&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/platform-tools&apos; (Expected &apos;/home/fabio/Android/platform-tools&apos;)
Observed package id &apos;platforms;android-30&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/platforms/android-30&apos; (Expected &apos;/home/fabio/Android/platforms/android-30&apos;)
Observed package id &apos;sources;android-30&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/sources/android-30&apos; (Expected &apos;/home/fabio/Android/sources/android-30&apos;)
Observed package id &apos;tools&apos; in inconsistent location &apos;/home/fabio/Android/Sdk/tools&apos; (Expected &apos;/home/fabio/Android/tools&apos;)

<b>&gt; Task :app:compileDebugJavaWithJavac</b>
Note: /home/fabio/Documentos/git/BlindOP/app/src/main/java/com/example/blindop/MainActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

<b>&gt; Task :app:compileReleaseJavaWithJavac</b>
Note: /home/fabio/Documentos/git/BlindOP/app/src/main/java/com/example/blindop/MainActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

<font color="#859900"><b>BUILD SUCCESSFUL</b></font> in 25s
49 actionable tasks: 49 executed
<font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ 

</pre>

<pre><font color="#859900"><b>fabio@fabio-13Z940-G-BK71P1</b></font>:<font color="#268BD2"><b>~/Documentos/git/BlindOP</b></font>$ sh gradlew assemble

<b>&gt; Configure project :app</b>
WARNING: Configuration &apos;compile&apos; is obsolete and has been replaced with &apos;implementation&apos; and &apos;api&apos;.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

<font color="#859900"><b>BUILD SUCCESSFUL</b></font> in 58s
44 actionable tasks: 6 executed, 38 up-to-date
</pre>
