### ISSUE TITLE
como incluir o retrofit no projeto?

### ISSUE THREAD

**Issue by FNakano** [shis218/BlindOP#2]
Como incluir retrofit no projeto?

**Comment by shis218** [comment]
No build.gradle de module:app
 adicione dentro das tags <manifest ...> </manifest ...>
implementation 'com.squareup.retrofit:retrofit:2.0.0-beta2'



e para importar nas classes java, use o 
import retrofit2.*;

**Comment by FNakano** [comment]
Ok, esta eu tento depois.

Lembrei que você teve algumas dúvidas sobre como usar retrofit e faltava documentação para orientar. Há alternativas para retrofit. Também é possível fazer requisições com Java, sem pacotes de terceiros. Talvez isto funcione enquanto as requisições forem simples.

Alternativas: https://www.twilio.com/blog/5-ways-to-make-http-requests-in-java

Classe URL (para GET): https://docs.oracle.com/javase/7/docs/api/java/net/URL.html

Classe HttpURLConnection (para todas as requisições): https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html

Tutorial usando HttpURL...: https://www.baeldung.com/java-http-request

Abraço!
