### ISSUE TITLE
Que arquivo deve ser ajustado e como?

### ISSUE THREAD

**Issue by FNakano** [shis218/BlindOP#3]
Que arquivo deve ser ajustado e como?

> Para utilizar a maioria dos recursos visuais do android, ele deve ser criado e colocado no Layout e então referenciado no arquivo java referente a Activity. Essas alterações no Layout são arquivos XML que caso não estejam mal escritos, podem ser visto no modo design do Android Studio.

**Comment by shis218** [comment]
O arquivo se encontra em /app/src/main/res/layout/activity_main.xml

Ele possui um botão de design na IDE que permite editar com interface grafica

**Comment by FNakano** [comment]
(enquanto estava escrevendo esta mensagem o autor respondeu.)

o arquivo é activity_main.xml e a inclusão é:
```xml
<TextView
            android:id="@+id/hwtxt"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Hello World!"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```
Instalei IntelliJ Idea, instalei o plugin para Android Studio, criei projeto com nome blindop, selecionei o layout bottom layout.

Além da inclusão acima, substituí o MainActivity.java pelo disponível neste projeto e comentei o import do retrofit (não deu erro pois os testes com retrofit estão comentados). 

Usando o botão "Build", o código é compilado mas o apk não é gerado. O menu "Build" tem uma opção explícita para gerar apk. 

Transferi o apk compartilhando pelo google Drive (em ocasião anterior, não consegui transferir apk através de G-mail). 

Executei o apk, o screenshot é:  

![Screenshot_20210403-155836_blindop](https://user-images.githubusercontent.com/14809968/113489260-a4c1bf00-9499-11eb-84ee-99073c963959.jpg)

Descomentei a linha da mensagem do TTS. Assim que a aplicação é aberta a mensagem é falada pelo celular.
